---
:project:
  :use_exceptions: FALSE
  :use_test_preprocessor: :tests
  :use_auxiliary_dependencies: TRUE
  :use_backtrace: :gdb
  :build_root: build
  :release_build: TRUE
  :test_file_prefix: test_
  :which_ce: .

:paths:
  :test:
    - +:tests/core/**
    - -:tests/ports/** # Explicitly ignore ports
    - -:tests/core/support
  :source:
    - src/core/**
    - include/**
  :include:
    - include/**
  :support:
    - tests/core/support/**
    - src/**

:defines:
  :test:
    - MEECORE_USE_PROJECT_CONFIG
    - TEST_MODE
  :test_preprocess:
    - MEECORE_USE_PROJECT_CONFIG
    - "SERIAL_IO_BUFFER_LENGTH=16"

:cmock:
  :mock_prefix: mock_
  :when_no_prototypes: :warn
  :enforce_strict_ordering: TRUE
  :plugins:
    - :ignore
    - :callback
    - :return_thru_ptr
    - :expect_any_args
    - :array
    - :ignore_arg
    - :cexception

:plugins:
  :enabled:
    - module_generator
    - report_tests_log_factory

:flags:
  :test:
    :compile:
      :add:
        - -Iinclude

:report_tests_log_factory:
  :reports:
    - cppunit

...